#!/bin/bash

# Build the React project
npm run build

# Check if the bucket exists
USER_BUCKET_NAME="user-$(git config user.name | tr '[:upper:]' '[:lower:]')-$(git symbolic-ref --short HEAD | tr '/' '-')"
if aws s3api head-bucket --bucket $USER_BUCKET_NAME --profile AccountLevelFullAccess-503226040441 2>/dev/null; then
  echo "Bucket already exists: $USER_BUCKET_NAME"
else
  echo "Creating bucket: $USER_BUCKET_NAME"
  aws s3api create-bucket --bucket $USER_BUCKET_NAME --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1 --profile AccountLevelFullAccess-503226040441
  aws s3api put-public-access-block --bucket $USER_BUCKET_NAME --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false" --profile AccountLevelFullAccess-503226040441
  aws s3api put-bucket-policy --bucket $USER_BUCKET_NAME --policy '{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Principal": "*",
        "Action": "s3:GetObject",
        "Resource": "arn:aws:s3:::'"$USER_BUCKET_NAME"'/*"
      }
    ]
  }' --profile AccountLevelFullAccess-503226040441
  aws s3api put-bucket-website --bucket $USER_BUCKET_NAME --website-configuration '{
    "ErrorDocument": {"Key": "index.html"},
    "IndexDocument": {"Suffix": "index.html"}
  }' --profile AccountLevelFullAccess-503226040441
fi

# Deploy the build to the user's branch-specific bucket
aws s3 sync build/ s3://$USER_BUCKET_NAME --profile AccountLevelFullAccess-503226040441

# Generate the deployment URL
DEPLOYMENT_URL="http://$USER_BUCKET_NAME.s3-website.ap-south-1.amazonaws.com"
echo "Deployment URL: $DEPLOYMENT_URL"



# Function to check if the JSON file exists in the bucket
check_json_file_exists() {
    local filename="$1"

    if aws s3 ls "s3://kdu-automation/frontend/$filename" --profile AccountLevelFullAccess-503226040441 &>/dev/null; then
        return 0  # File exists
    else
        return 1  # File does not exist
    fi
}

# Function to add or update key-value pair in JSON object using jq
add_key_value_to_json() {
    local key="$1"
    local value="$2"
    local json_file="$3"

    if jq --exit-status --arg key "$key" --arg value "$value" '.[$key] |= $value' "$json_file"; then
        # If the key exists, update the value
        jq --arg key "$key" --arg value "$value" '.[$key] |= $value' "$json_file" > "$json_file.tmp"
    else
        # If the key doesn't exist, add the new key-value pair to the JSON object
        jq --arg key "$key" --arg value "$value" '. + { ($key): $value }' "$json_file" > "$json_file.tmp"
    fi
    mv "$json_file.tmp" "$json_file"
}



# Update JSON file with the deployment URL
USERNAME=$(git config user.name)
#BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="exercise-11"
FILENAME="submissions.json"

# Check if the JSON file exists in the bucket
if check_json_file_exists "$FILENAME"; then
    # Download the JSON file from the bucket
    aws s3 cp "s3://kdu-automation/frontend/$FILENAME" ./temp.json --profile AccountLevelFullAccess-503226040441
else
    # Create a new empty JSON file if it doesn't exist in the bucket
    echo "{}" > ./temp.json
fi

# Add or update the key-value pair in the JSON object
KEY="$USERNAME-$BRANCH_NAME"
VALUE="$DEPLOYMENT_URL"  # Remove the escaped double quotes here

add_key_value_to_json "$KEY" "$VALUE" ./temp.json

# Upload the updated JSON file back to the bucket
aws s3 cp ./temp.json "s3://kdu-automation/frontend/$FILENAME" --profile AccountLevelFullAccess-503226040441

echo "JSON file uploaded successfully."


